# Cloud-optimized training configuration
cloud:
  instance_type: "rtx4090"
  storage_path: "/workspace"
  checkpoint_interval: 100_000_000  # Every 100M tokens
  max_checkpoints: 10

stage1:
  # Text pretrain - 2B tokens
  dataset_path: "data/tokenized/cloud/stage1.bin"
  idx_path: "data/tokenized/cloud/stage1.idx"
  tokenizer_path: "artifacts/tokenizer/fustercluck.model"
  max_steps: 4000
  seq_len: 4096
  micro_batch_size: 2
  gradient_accumulation: 64
  effective_batch_size: 524288  # 4096 * 2 * 64
  precision: bf16
  log_interval: 20
  eval_interval: 500
  checkpoint_dir: "artifacts/checkpoints/cloud/stage1"
  model_dim: 1024
  model_layers: 24
  model_heads: 16
  model_kv_heads: 4
  mlp_ratio: 4.0
  rope_theta: 10000
  dropout: 0.0
  optimizer:
    lr: 2.5e-4
    betas: [0.9, 0.95]
    weight_decay: 0.1
    eps: 1e-8
  lr_schedule:
    type: "cosine"
    warmup_steps: 2000
    min_lr: 2.5e-5
  grad_clip: 1.0
  target_tokens: 2_000_000_000

stage2:
  # Text pretrain - 5B tokens
  dataset_path: "data/tokenized/cloud/stage2.bin"
  idx_path: "data/tokenized/cloud/stage2.idx"
  tokenizer_path: "artifacts/tokenizer/fustercluck.model"
  max_steps: 10000
  seq_len: 4096
  micro_batch_size: 2
  gradient_accumulation: 64
  effective_batch_size: 524288
  precision: bf16
  log_interval: 20
  eval_interval: 500
  checkpoint_dir: "artifacts/checkpoints/cloud/stage2"
  model_dim: 1024
  model_layers: 24
  model_heads: 16
  model_kv_heads: 4
  mlp_ratio: 4.0
  rope_theta: 10000
  dropout: 0.0
  optimizer:
    lr: 2.0e-4  # Slightly lower LR for stage 2
    betas: [0.9, 0.95]
    weight_decay: 0.1
    eps: 1e-8
  lr_schedule:
    type: "cosine"
    warmup_steps: 2000
    min_lr: 2.0e-5
  grad_clip: 1.0
  target_tokens: 5_000_000_000

trainer:
  device: cuda
  use_compile: true
  compile_mode: "reduce-overhead"
  precision: bf16
  gradient_checkpointing: true
  activation_recompute: true
  dataloader_workers: 16
  pin_memory: true
  persistent_workers: true
  env:
    PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True"
    TORCH_CUDA_FUSER_DISABLE: "1"
    TORCHINDUCTOR_MAX_AUTOTUNE_GEMM_TUNERS: "0"
    TORCHINDUCTOR_MAX_AUTOTUNE_LOCATIONS: "0"
    TORCHINDUCTOR_MAX_AUTOTUNE: "0"
  checkpoint:
    directory: "artifacts/checkpoints/cloud"
    keep_last: 10
    save_optimizer: true
    save_scheduler: true

monitoring:
  wandb:
    project: "fustercluck-cloud"
    entity: null
    tags: ["cloud", "pretrain", "rtx4090"]
  tensorboard:
    log_dir: "logs/tensorboard"
  metrics:
    - "loss"
    - "perplexity"
    - "tokens_per_second"
    - "memory_usage"
    - "gpu_utilization"
