stage:
  dataset_path: data/tokenized/stage0.bin
  idx_path: data/tokenized/stage0.idx
  tokenizer_path: artifacts/tokenizer/fustercluck.model
  max_steps: 10000
  seq_len: 12288
  micro_batch_size: 1
  gradient_accumulation: 32
  precision: bf16
  log_interval: 20
  eval_interval: 200
  checkpoint_dir: artifacts/checkpoints/stage0
  model_dim: 896
  model_layers: 18
  model_heads: 14
  model_kv_heads: 2
  mlp_ratio: 3.5
  rope_theta: 10000
  dropout: 0.0
  optimizer:
    lr: 0.0002
    betas: [0.9, 0.95]
    weight_decay: 0.1
trainer:
  device: mps
  grad_clip: 1.0
  use_compile: false
  compile_mode: reduce-overhead
  precision: bf16
  gradient_checkpointing: true
  checkpoint:
    directory: artifacts/checkpoints/stage0
    keep_last: 5
