stage0:
  dataset_path: data/tokenized/stage0.bin
  idx_path: data/tokenized/stage0.idx
  tokenizer_path: artifacts/tokenizer/fustercluck.model
  max_steps: 2000
  seq_len: 1408
  micro_batch_size: 4
  gradient_accumulation: 8
  precision: bf16
  log_interval: 20
  eval_interval: 200
  checkpoint_dir: artifacts/checkpoints/stage0
  optimizer:
    lr: 0.00025
    betas: [0.9, 0.95]
    weight_decay: 0.1
trainer:
  device: mps
  grad_clip: 1.0
  use_compile: true
  compile_mode: reduce-overhead
  precision: bf16
  checkpoint:
    directory: artifacts/checkpoints/stage0
    keep_last: 5
